service:
  name: asdev-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  profile: ${self:custom.config.AWS_PROFILE}

custom:
  config: ${file(./secrets.yml)}
  alexa:
    # Step 1: Run `sls alexa auth` to authenticate
    # Step 2: Run `sls alexa create --name "Serverless Alexa Typescript" --locale en-GB --type custom` to create a new skill
    skills:
      # Step 3: Paste the skill id returned by the create command here:
      - id: amzn1.ask.skill.${self:custom.config.SKILL_ID_0}
        manifest:
          publishingInformation:
            locales:
              ja-JP:
                name: Serverless Alexa Typescript
          permissions:
            - name: alexa::devices:all:address:full:read
          apis:
            custom:
              endpoint:
                # Step 4: Do your first deploy of your Serverless stack
                # Step 5: Paste the ARN of your lambda here:
                uri: arn:aws:lambda:ap-northeast-1:${self:custom.config.AWS_ACCOUNT_ID}:function:${self:custom.config.FUNCTION_NAME}
                # Step 6: Run `sls alexa update` to deploy the skill manifest
                # Step 7: Run `sls alexa build` to build the skill interaction model
                # Step 8: Enable the skill in the Alexa app to start testing.
          manifestVersion: '1.0'
        models:
          ja-JP:
            interactionModel:
              languageModel:
                invocationName: 'ゴミスキル'
                intents:
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []
                  - name: garbageDateIntent
                    slots:
                      - name: targetDate
                        type: AMAZON.DATE
                    samples:
                    - '{targetDate} のゴミを教えて'
                    - '{targetDate} のゴミは'
                    - '{targetDate} のゴミは何'
functions:
  garbageSkill:
    handler: garbageSkill.handler
    events:
      - alexaSkill: ${self:custom.alexa.skills.0.id}
